export const ACHIEVEMENT_DEFINITIONS = [
  { code: "ROCKET_START",     name: "Ракетный старт",        icon: "🚀", description: "Поднялся на 3+ позиции в первом круге" },
  { code: "DOMINATOR",        name: "Доминатор",             icon: "👑", description: "3 победы подряд" },
  { code: "RAIN_MASTER",      name: "Мастер дождя",          icon: "🌧", description: "Победа в дождевой гонке" },
  { code: "WRECKING_BALL",    name: "Таран",                 icon: "💥", description: "3+ штрафа за одну гонку" },
  { code: "SPEED_DEMON",      name: "Демон скорости",        icon: "⚡", description: "Абсолютный рекорд сезона по FL" },
  { code: "PHOTO_FINISH",     name: "Фотофиниш",            icon: "📸", description: "Финиш < 0.5с от соперника" },
  { code: "LAST_TO_FIRST",    name: "С последнего на первое", icon: "🔄", description: "Победа с последнего места" },
  { code: "CLEAN_SWEEP",      name: "Полный уик-энд",        icon: "🧹", description: "Поул + FL + победа" },
  { code: "CONSISTENCY_KING", name: "Король стабильности",   icon: "🎯", description: "5 гонок подряд в топ-3" },
  { code: "GIANT_KILLER",     name: "Убийца гигантов",       icon: "🗡", description: "Финиш выше лидера WDC" },
  { code: "PIT_MASTER",       name: "Мастер пит-стопа",      icon: "🔧", description: "Подъём после пит-стопа" },
  { code: "SURVIVOR",         name: "Выживший",              icon: "🛡", description: "Финиш при 2+ DNF людей" },
  { code: "FIRST_BLOOD",      name: "Первая победа",         icon: "🏆", description: "Первая победа в карьере" },
  { code: "CENTURION",        name: "Центурион",             icon: "💯", description: "100+ очков за сезон" },
  { code: "COMEBACK_KID",     name: "Мастер камбэка",        icon: "🔥", description: "Подиум с P10+" },
  { code: "THE_WALL",         name: "Стена",                 icon: "🧱", description: "Сезон без штрафов" },
  { code: "WEEKEND_WARRIOR",  name: "Воин уик-энда",         icon: "⚔️", description: "3+ гонки за день" },
  { code: "HEARTBREAKER",     name: "Разбитые надежды",      icon: "💔", description: "DNF из топ-5" },
  { code: "BOT_SLAYER",       name: "Гроза ботов",           icon: "🤖", description: "Выше Verstappen 5+ раз" },
  { code: "TEAMPLAYER",       name: "Командный игрок",       icon: "🤝", description: "Команда в топ-3 WCC" },
  { code: "CHAMPION",         name: "Чемпион",               icon: "🏅", description: "Чемпион WDC" },
  { code: "OVERTAKE_KING",    name: "Король обгонов",        icon: "💨", description: "Больше всех обгонов" },
  // New race
  { code: "GRAND_CHELEM",     name: "Гранд челлем",         icon: "🏅", description: "Поул + лидерство + FL + победа" },
  { code: "UNDERDOG",         name: "Андердог",             icon: "🐕", description: "Победа с P15+" },
  { code: "SAFETY_CAR_KING",  name: "Король SC",            icon: "🟡", description: "+3 позиции после SC" },
  { code: "RAIN_DANCE",       name: "Танец дождя",          icon: "🌊", description: "3+ мокрых подиума" },
  { code: "LIGHTS_OUT",       name: "Гашение огней",        icon: "💡", description: "Лучший старт сезона" },
  { code: "LATE_BRAKER",      name: "Позднее торможение",   icon: "⏱", description: "Обгон за подиум" },
  { code: "DOUBLE_POINTS",    name: "Двойные очки",         icon: "🎰", description: "2 подиума за вечер" },
  { code: "MARATHON_MAN",     name: "Марафонец",            icon: "🏃", description: "4+ гонки в очках подряд" },
  { code: "PENALTY_FREE",     name: "Без штрафов",          icon: "🕊", description: "10 гонок без штрафов" },
  { code: "TEAM_ORDERS",      name: "Командные приказы",    icon: "📋", description: "Оба в команде на подиуме" },
  { code: "THE_STIG",         name: "Стиг",                 icon: "🏁", description: "Победа с отрывом 10+ сек" },
  { code: "BULLDOZER",        name: "Бульдозер",            icon: "🚜", description: "P1 среди всех людей" },
  // Progression
  { code: "RISING_STAR",      name: "Восходящая звезда",    icon: "⭐", description: "5 гонок подряд вверх" },
  { code: "HOT_STREAK",       name: "Горячая серия",        icon: "🔥", description: "3 победы за вечер" },
  { code: "FIFTY_RACES",      name: "50 гонок",             icon: "5️⃣", description: "50 гонок в карьере" },
  { code: "HUNDRED_RACES",    name: "100 гонок",            icon: "💯", description: "100 гонок в карьере" },
  { code: "POINTS_MACHINE",   name: "Машина очков",         icon: "⚙️", description: "10 гонок в очках подряд" },
  { code: "TWO_HUNDRED_PTS",  name: "200 очков",            icon: "💎", description: "200+ очков за сезон" },
  { code: "VETERAN",          name: "Ветеран",              icon: "🎖", description: "3+ сезона" },
  // Fun
  { code: "TORPEDO",          name: "Торпеда",              icon: "🚇", description: "3+ столкновения за гонку" },
  { code: "GLASS_CANNON",     name: "Стеклянная пушка",     icon: "🔮", description: "FL + DNF в одной гонке" },
  { code: "REVERSE_GRID",     name: "Обратная решетка",     icon: "🔃", description: "5x финиш ниже грида" },
  { code: "SUNDAY_DRIVER",    name: "Воскресный пилот",     icon: "🐌", description: "Самый медленный 3x подряд" },
  { code: "LAST_NOT_LEAST",   name: "Последний, но не худший", icon: "🥉", description: "Последний человек, выше 10 AI" },
  { code: "JINXED",           name: "Проклятый",            icon: "🫠", description: "3 DNF подряд" },
  { code: "PHOENIX",          name: "Феникс",               icon: "🔥", description: "Подиум после 3 DNF" },
  { code: "GENTLEMAN",        name: "Джентльмен",           icon: "🎩", description: "0 столкновений за сезон" },
  // Exclusive
  { code: "FOUNDING_FATHER",  name: "Основатель",           icon: "🏛", description: "Первая гонка в системе" },
  { code: "ARCHITECT",        name: "Архитектор",           icon: "🏗", description: "Лобби с 10+ гонками" },
  { code: "POPULAR_CHOICE",   name: "Выбор паддока",        icon: "👥", description: "5+ людей в лобби" },
]
